// Snapshots the local database into server/seed.sql so it travels with the code.
// Run `npm run seed:export` while the local server is running, then commit seed.sql.
// On start the API applies the file whenever its contents changed (see index.mjs).
import pg from "pg";
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PG_PORT = Number(process.env.PG_PORT || 5433);
const out = path.join(__dirname, "seed.sql");

const client = new pg.Client({
  host: "127.0.0.1",
  port: PG_PORT,
  user: "pss",
  password: "pss",
  database: "pss_attendance",
  connectionTimeoutMillis: 3000,
});

try {
  await client.connect();
} catch {
  console.error(`Could not reach PostgreSQL on 127.0.0.1:${PG_PORT}. Start the app first (npm run dev or npm run server).`);
  process.exit(1);
}

const lit = (value) => {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "boolean") return value ? "TRUE" : "FALSE";
  if (typeof value === "number") return String(value);
  if (value instanceof Date) return `'${value.toISOString()}'::timestamptz`;
  if (Array.isArray(value)) return `ARRAY[${value.map((item) => lit(item)).join(", ")}]::text[]`;
  return `'${String(value).replace(/'/g, "''")}'`;
};

const row = (table, columns, values, conflict) =>
  `INSERT INTO ${table} (${columns.join(", ")})\nVALUES (${values.map(lit).join(", ")})\n${conflict};\n`;

const lines = ["-- Bundled database snapshot. Generated by `npm run seed:export`; applied on start whenever it changes.", ""];

// People first: existing rows keep the password set on the server, everything else follows the snapshot.
const people = await client.query(
  `SELECT user_id, name, username, email, password, role, team, teams, active, to_char(joined, 'YYYY-MM-DD') AS joined,
          late_allowed, work_mode, officer, mto, reports_to
   FROM people ORDER BY user_id`
);
const peopleCols = ["user_id", "name", "username", "email", "password", "role", "team", "teams", "active", "joined", "late_allowed", "work_mode", "officer", "mto"];
for (const p of people.rows) {
  lines.push(
    row(
      "people",
      peopleCols,
      peopleCols.map((col) => p[col]),
      `ON CONFLICT (user_id) DO UPDATE SET
  name = EXCLUDED.name,
  username = EXCLUDED.username,
  email = EXCLUDED.email,
  role = EXCLUDED.role,
  team = EXCLUDED.team,
  teams = EXCLUDED.teams,
  active = EXCLUDED.active,
  joined = EXCLUDED.joined,
  late_allowed = EXCLUDED.late_allowed,
  work_mode = EXCLUDED.work_mode,
  officer = EXCLUDED.officer,
  mto = EXCLUDED.mto`
    )
  );
}
// reports_to points at other people, so it is set after everyone exists.
for (const p of people.rows) {
  if (p.reports_to) lines.push(`UPDATE people SET reports_to = ${lit(p.reports_to)} WHERE user_id = ${lit(p.user_id)};\n`);
}

const attendance = await client.query(
  `SELECT user_id, to_char(date, 'YYYY-MM-DD') AS date, check_in, check_out, late, worked_minutes, marked_present
   FROM attendance ORDER BY date, user_id`
);
const attendanceCols = ["user_id", "date", "check_in", "check_out", "late", "worked_minutes", "marked_present"];
for (const a of attendance.rows) {
  lines.push(row("attendance", attendanceCols, attendanceCols.map((col) => a[col]), "ON CONFLICT (user_id, date) DO NOTHING"));
}

const leave = await client.query(
  `SELECT id, user_id, to_char(from_date, 'YYYY-MM-DD') AS from_date, to_char(to_date, 'YYYY-MM-DD') AS to_date,
          reason, status, rejection_reason
   FROM leave_requests ORDER BY from_date, id`
);
const leaveCols = ["id", "user_id", "from_date", "to_date", "reason", "status", "rejection_reason"];
for (const l of leave.rows) {
  lines.push(row("leave_requests", leaveCols, leaveCols.map((col) => l[col]), "ON CONFLICT (id) DO NOTHING"));
}

const tasks = await client.query(
  `SELECT id, title, brief, description, assignee_user_id, status, priority, to_char(due_date, 'YYYY-MM-DD') AS due_date,
          created_by, created_at, updated_at, completed_at
   FROM tasks ORDER BY created_at, id`
);
const taskCols = ["id", "title", "brief", "description", "assignee_user_id", "status", "priority", "due_date", "created_by", "created_at", "updated_at", "completed_at"];
for (const t of tasks.rows) {
  lines.push(row("tasks", taskCols, taskCols.map((col) => t[col]), "ON CONFLICT (id) DO NOTHING"));
}

const comments = await client.query(
  `SELECT id, task_id, author_user_id, body, kind, to_char(entry_date, 'YYYY-MM-DD') AS entry_date, created_at
   FROM task_comments ORDER BY created_at, id`
);
const commentCols = ["id", "task_id", "author_user_id", "body", "kind", "entry_date", "created_at"];
for (const c of comments.rows) {
  lines.push(row("task_comments", commentCols, commentCols.map((col) => c[col]), "ON CONFLICT (id) DO NOTHING"));
}

const activity = await client.query(
  `SELECT id, task_id, actor_user_id, kind, detail, created_at FROM task_activity ORDER BY created_at, id`
);
const activityCols = ["id", "task_id", "actor_user_id", "kind", "detail", "created_at"];
for (const a of activity.rows) {
  lines.push(row("task_activity", activityCols, activityCols.map((col) => a[col]), "ON CONFLICT (id) DO NOTHING"));
}

const sheetDays = await client.query(`SELECT to_char(day, 'YYYY-MM-DD') AS day, added_by, created_at FROM sheet_days ORDER BY day`);
const sheetCols = ["day", "added_by", "created_at"];
for (const d of sheetDays.rows) {
  lines.push(row("sheet_days", sheetCols, sheetCols.map((col) => d[col]), "ON CONFLICT (day) DO NOTHING"));
}

await client.end();
writeFileSync(out, lines.join("\n"), "utf8");
console.log(
  `Wrote ${path.relative(process.cwd(), out)}: ${people.rowCount} people, ${attendance.rowCount} attendance, ${leave.rowCount} leave, ` +
    `${tasks.rowCount} tasks, ${comments.rowCount} comments, ${activity.rowCount} activity, ${sheetDays.rowCount} sheet days.`
);
