-- Bundled database snapshot. Generated by `npm run seed:export`; applied on start whenever it changes.

INSERT INTO people (user_id, name, username, email, password, role, team, teams, active, joined, late_allowed, work_mode, officer, mto)
VALUES ('HR001', 'HR', 'hr', 'hr@pss.local', 'hr123456', 'hr', NULL, ARRAY[]::text[], TRUE, '2026-10-02', FALSE, NULL, FALSE, FALSE)
ON CONFLICT (user_id) DO UPDATE SET
  name = EXCLUDED.name,
  username = EXCLUDED.username,
  email = EXCLUDED.email,
  role = EXCLUDED.role,
  team = EXCLUDED.team,
  teams = EXCLUDED.teams,
  active = EXCLUDED.active,
  joined = EXCLUDED.joined,
  late_allowed = EXCLUDED.late_allowed,
  work_mode = EXCLUDED.work_mode,
  officer = EXCLUDED.officer,
  mto = EXCLUDED.mto;

INSERT INTO people (user_id, name, username, email, password, role, team, teams, active, joined, late_allowed, work_mode, officer, mto)
VALUES ('HR002', 'HR PSS', 'hr-pss', 'hr-pss@pss.local', 'hr123456', 'hr', NULL, ARRAY[]::text[], TRUE, '2026-10-02', FALSE, NULL, FALSE, FALSE)
ON CONFLICT (user_id) DO UPDATE SET
  name = EXCLUDED.name,
  username = EXCLUDED.username,
  email = EXCLUDED.email,
  role = EXCLUDED.role,
  team = EXCLUDED.team,
  teams = EXCLUDED.teams,
  active = EXCLUDED.active,
  joined = EXCLUDED.joined,
  late_allowed = EXCLUDED.late_allowed,
  work_mode = EXCLUDED.work_mode,
  officer = EXCLUDED.officer,
  mto = EXCLUDED.mto;

INSERT INTO people (user_id, name, username, email, password, role, team, teams, active, joined, late_allowed, work_mode, officer, mto)
VALUES ('PSS001', 'PSS Admin', 'admin', 'admin@pss.local', 'admin123', 'admin', NULL, ARRAY[]::text[], TRUE, '2026-09-24', FALSE, NULL, FALSE, FALSE)
ON CONFLICT (user_id) DO UPDATE SET
  name = EXCLUDED.name,
  username = EXCLUDED.username,
  email = EXCLUDED.email,
  role = EXCLUDED.role,
  team = EXCLUDED.team,
  teams = EXCLUDED.teams,
  active = EXCLUDED.active,
  joined = EXCLUDED.joined,
  late_allowed = EXCLUDED.late_allowed,
  work_mode = EXCLUDED.work_mode,
  officer = EXCLUDED.officer,
  mto = EXCLUDED.mto;

INSERT INTO people (user_id, name, username, email, password, role, team, teams, active, joined, late_allowed, work_mode, officer, mto)
VALUES ('PSS002', 'Hassan Azwar', 'hassanazwar', 'hassanazwar@local.pss', '123123123', 'admin', NULL, ARRAY[]::text[], TRUE, '2026-09-25', FALSE, NULL, FALSE, FALSE)
ON CONFLICT (user_id) DO UPDATE SET
  name = EXCLUDED.name,
  username = EXCLUDED.username,
  email = EXCLUDED.email,
  role = EXCLUDED.role,
  team = EXCLUDED.team,
  teams = EXCLUDED.teams,
  active = EXCLUDED.active,
  joined = EXCLUDED.joined,
  late_allowed = EXCLUDED.late_allowed,
  work_mode = EXCLUDED.work_mode,
  officer = EXCLUDED.officer,
  mto = EXCLUDED.mto;

INSERT INTO people (user_id, name, username, email, password, role, team, teams, active, joined, late_allowed, work_mode, officer, mto)
VALUES ('PSS003', 'Taymur Iqbal', 'taymuriqbal', 'taymuriqbal@local.pss', '123123123', 'team_lead', 'ops', ARRAY['ops']::text[], TRUE, '2026-09-25', FALSE, NULL, TRUE, FALSE)
ON CONFLICT (user_id) DO UPDATE SET
  name = EXCLUDED.name,
  username = EXCLUDED.username,
  email = EXCLUDED.email,
  role = EXCLUDED.role,
  team = EXCLUDED.team,
  teams = EXCLUDED.teams,
  active = EXCLUDED.active,
  joined = EXCLUDED.joined,
  late_allowed = EXCLUDED.late_allowed,
  work_mode = EXCLUDED.work_mode,
  officer = EXCLUDED.officer,
  mto = EXCLUDED.mto;

INSERT INTO people (user_id, name, username, email, password, role, team, teams, active, joined, late_allowed, work_mode, officer, mto)
VALUES ('PSS004', 'Hanan Jatoi', 'hananjatoi', 'hananjatoi@local.pss', '123123123', 'team_lead', 'defensive', ARRAY['defensive', 'ops']::text[], TRUE, '2026-09-25', FALSE, NULL, TRUE, FALSE)
ON CONFLICT (user_id) DO UPDATE SET
  name = EXCLUDED.name,
  username = EXCLUDED.username,
  email = EXCLUDED.email,
  role = EXCLUDED.role,
  team = EXCLUDED.team,
  teams = EXCLUDED.teams,
  active = EXCLUDED.active,
  joined = EXCLUDED.joined,
  late_allowed = EXCLUDED.late_allowed,
  work_mode = EXCLUDED.work_mode,
  officer = EXCLUDED.officer,
  mto = EXCLUDED.mto;

INSERT INTO people (user_id, name, username, email, password, role, team, teams, active, joined, late_allowed, work_mode, officer, mto)
VALUES ('PSS005', 'Nawal Ali', 'nawal', 'nawal@local.pss', '123123123', 'team_lead', 'product', ARRAY['product']::text[], TRUE, '2026-09-25', FALSE, NULL, TRUE, FALSE)
ON CONFLICT (user_id) DO UPDATE SET
  name = EXCLUDED.name,
  username = EXCLUDED.username,
  email = EXCLUDED.email,
  role = EXCLUDED.role,
  team = EXCLUDED.team,
  teams = EXCLUDED.teams,
  active = EXCLUDED.active,
  joined = EXCLUDED.joined,
  late_allowed = EXCLUDED.late_allowed,
  work_mode = EXCLUDED.work_mode,
  officer = EXCLUDED.officer,
  mto = EXCLUDED.mto;

INSERT INTO people (user_id, name, username, email, password, role, team, teams, active, joined, late_allowed, work_mode, officer, mto)
VALUES ('PSS006', 'Saad Amin', 'saadamin', 'saadminz@local.pss', '123123123', 'team_lead', 'product', ARRAY['product']::text[], TRUE, '2026-09-25', FALSE, NULL, FALSE, FALSE)
ON CONFLICT (user_id) DO UPDATE SET
  name = EXCLUDED.name,
  username = EXCLUDED.username,
  email = EXCLUDED.email,
  role = EXCLUDED.role,
  team = EXCLUDED.team,
  teams = EXCLUDED.teams,
  active = EXCLUDED.active,
  joined = EXCLUDED.joined,
  late_allowed = EXCLUDED.late_allowed,
  work_mode = EXCLUDED.work_mode,
  officer = EXCLUDED.officer,
  mto = EXCLUDED.mto;

INSERT INTO people (user_id, name, username, email, password, role, team, teams, active, joined, late_allowed, work_mode, officer, mto)
VALUES ('PSS007', 'Tanjeena Manzoor', 'tanjeenamanzoor', 'tanjeena@local.pss', '123123123', 'team_lead', 'product', ARRAY['product']::text[], TRUE, '2026-09-25', FALSE, NULL, TRUE, FALSE)
ON CONFLICT (user_id) DO UPDATE SET
  name = EXCLUDED.name,
  username = EXCLUDED.username,
  email = EXCLUDED.email,
  role = EXCLUDED.role,
  team = EXCLUDED.team,
  teams = EXCLUDED.teams,
  active = EXCLUDED.active,
  joined = EXCLUDED.joined,
  late_allowed = EXCLUDED.late_allowed,
  work_mode = EXCLUDED.work_mode,
  officer = EXCLUDED.officer,
  mto = EXCLUDED.mto;

INSERT INTO people (user_id, name, username, email, password, role, team, teams, active, joined, late_allowed, work_mode, officer, mto)
VALUES ('PSS008', 'Zainab', 'zaynab', 'zaynab@local.pss', '123123123', 'employee', 'product', ARRAY['product']::text[], TRUE, '2026-09-27', FALSE, NULL, FALSE, TRUE)
ON CONFLICT (user_id) DO UPDATE SET
  name = EXCLUDED.name,
  username = EXCLUDED.username,
  email = EXCLUDED.email,
  role = EXCLUDED.role,
  team = EXCLUDED.team,
  teams = EXCLUDED.teams,
  active = EXCLUDED.active,
  joined = EXCLUDED.joined,
  late_allowed = EXCLUDED.late_allowed,
  work_mode = EXCLUDED.work_mode,
  officer = EXCLUDED.officer,
  mto = EXCLUDED.mto;

INSERT INTO people (user_id, name, username, email, password, role, team, teams, active, joined, late_allowed, work_mode, officer, mto)
VALUES ('PSS009', 'Ikhtiar Ali', 'ikhtiar', 'ikhtiar@local.pss', '123123123', 'officer', 'ops', ARRAY['ops']::text[], TRUE, '2026-09-27', FALSE, NULL, FALSE, FALSE)
ON CONFLICT (user_id) DO UPDATE SET
  name = EXCLUDED.name,
  username = EXCLUDED.username,
  email = EXCLUDED.email,
  role = EXCLUDED.role,
  team = EXCLUDED.team,
  teams = EXCLUDED.teams,
  active = EXCLUDED.active,
  joined = EXCLUDED.joined,
  late_allowed = EXCLUDED.late_allowed,
  work_mode = EXCLUDED.work_mode,
  officer = EXCLUDED.officer,
  mto = EXCLUDED.mto;

INSERT INTO people (user_id, name, username, email, password, role, team, teams, active, joined, late_allowed, work_mode, officer, mto)
VALUES ('PSS010', 'Yousaf Sani', 'yousafsani', 'yousafsani@local.pss', '123123123', 'team_lead', 'offensive', ARRAY['offensive']::text[], TRUE, '2026-09-27', TRUE, NULL, FALSE, FALSE)
ON CONFLICT (user_id) DO UPDATE SET
  name = EXCLUDED.name,
  username = EXCLUDED.username,
  email = EXCLUDED.email,
  role = EXCLUDED.role,
  team = EXCLUDED.team,
  teams = EXCLUDED.teams,
  active = EXCLUDED.active,
  joined = EXCLUDED.joined,
  late_allowed = EXCLUDED.late_allowed,
  work_mode = EXCLUDED.work_mode,
  officer = EXCLUDED.officer,
  mto = EXCLUDED.mto;

INSERT INTO people (user_id, name, username, email, password, role, team, teams, active, joined, late_allowed, work_mode, officer, mto)
VALUES ('PSS011', 'Sultan Umar Cheema', 'sultan_cheema', 'sultancheema@local.pss', '123123123', 'team_lead', 'offensive', ARRAY['offensive']::text[], TRUE, '2026-09-27', FALSE, NULL, FALSE, TRUE)
ON CONFLICT (user_id) DO UPDATE SET
  name = EXCLUDED.name,
  username = EXCLUDED.username,
  email = EXCLUDED.email,
  role = EXCLUDED.role,
  team = EXCLUDED.team,
  teams = EXCLUDED.teams,
  active = EXCLUDED.active,
  joined = EXCLUDED.joined,
  late_allowed = EXCLUDED.late_allowed,
  work_mode = EXCLUDED.work_mode,
  officer = EXCLUDED.officer,
  mto = EXCLUDED.mto;

INSERT INTO people (user_id, name, username, email, password, role, team, teams, active, joined, late_allowed, work_mode, officer, mto)
VALUES ('PSS012', 'Jalal Khan', 'jalal_khan', 'jalalkhan@local.pss', '123123123', 'employee', 'ops', ARRAY['ops']::text[], TRUE, '2026-09-27', FALSE, NULL, FALSE, FALSE)
ON CONFLICT (user_id) DO UPDATE SET
  name = EXCLUDED.name,
  username = EXCLUDED.username,
  email = EXCLUDED.email,
  role = EXCLUDED.role,
  team = EXCLUDED.team,
  teams = EXCLUDED.teams,
  active = EXCLUDED.active,
  joined = EXCLUDED.joined,
  late_allowed = EXCLUDED.late_allowed,
  work_mode = EXCLUDED.work_mode,
  officer = EXCLUDED.officer,
  mto = EXCLUDED.mto;

INSERT INTO people (user_id, name, username, email, password, role, team, teams, active, joined, late_allowed, work_mode, officer, mto)
VALUES ('PSS013', 'Abeera Zainab', 'abeera_zainab', 'abeerazainab@local.pss', '123123123', 'employee', 'product', ARRAY['product']::text[], TRUE, '2026-09-27', FALSE, NULL, FALSE, FALSE)
ON CONFLICT (user_id) DO UPDATE SET
  name = EXCLUDED.name,
  username = EXCLUDED.username,
  email = EXCLUDED.email,
  role = EXCLUDED.role,
  team = EXCLUDED.team,
  teams = EXCLUDED.teams,
  active = EXCLUDED.active,
  joined = EXCLUDED.joined,
  late_allowed = EXCLUDED.late_allowed,
  work_mode = EXCLUDED.work_mode,
  officer = EXCLUDED.officer,
  mto = EXCLUDED.mto;

INSERT INTO people (user_id, name, username, email, password, role, team, teams, active, joined, late_allowed, work_mode, officer, mto)
VALUES ('PSS014', 'Lubna Basharat', 'lubna_basharat', 'lubnabasharat@local.pss', '123123123', 'employee', 'product', ARRAY['product']::text[], TRUE, '2026-09-27', FALSE, NULL, FALSE, FALSE)
ON CONFLICT (user_id) DO UPDATE SET
  name = EXCLUDED.name,
  username = EXCLUDED.username,
  email = EXCLUDED.email,
  role = EXCLUDED.role,
  team = EXCLUDED.team,
  teams = EXCLUDED.teams,
  active = EXCLUDED.active,
  joined = EXCLUDED.joined,
  late_allowed = EXCLUDED.late_allowed,
  work_mode = EXCLUDED.work_mode,
  officer = EXCLUDED.officer,
  mto = EXCLUDED.mto;

INSERT INTO people (user_id, name, username, email, password, role, team, teams, active, joined, late_allowed, work_mode, officer, mto)
VALUES ('PSS015', 'Talha Obaid', 'talha_obaid', 'talhaobaid@local.pss', '123123123', 'team_lead', 'defensive', ARRAY['defensive', 'ops']::text[], TRUE, '2026-09-27', TRUE, NULL, FALSE, FALSE)
ON CONFLICT (user_id) DO UPDATE SET
  name = EXCLUDED.name,
  username = EXCLUDED.username,
  email = EXCLUDED.email,
  role = EXCLUDED.role,
  team = EXCLUDED.team,
  teams = EXCLUDED.teams,
  active = EXCLUDED.active,
  joined = EXCLUDED.joined,
  late_allowed = EXCLUDED.late_allowed,
  work_mode = EXCLUDED.work_mode,
  officer = EXCLUDED.officer,
  mto = EXCLUDED.mto;

INSERT INTO people (user_id, name, username, email, password, role, team, teams, active, joined, late_allowed, work_mode, officer, mto)
VALUES ('PSS016', 'Abdullah Nadeem', 'abdullah_nadeem', 'abdullahnadeem@local.pss', 'Qw3Rty345', 'employee', 'ops', ARRAY['ops', 'defensive']::text[], TRUE, '2026-09-27', FALSE, NULL, FALSE, FALSE)
ON CONFLICT (user_id) DO UPDATE SET
  name = EXCLUDED.name,
  username = EXCLUDED.username,
  email = EXCLUDED.email,
  role = EXCLUDED.role,
  team = EXCLUDED.team,
  teams = EXCLUDED.teams,
  active = EXCLUDED.active,
  joined = EXCLUDED.joined,
  late_allowed = EXCLUDED.late_allowed,
  work_mode = EXCLUDED.work_mode,
  officer = EXCLUDED.officer,
  mto = EXCLUDED.mto;

INSERT INTO people (user_id, name, username, email, password, role, team, teams, active, joined, late_allowed, work_mode, officer, mto)
VALUES ('PSS017', 'Haroon Allahdad', 'haroon_allahdad', 'haroonniftac@gmail.com', '123123123', 'employee', 'defensive', ARRAY['defensive', 'ops']::text[], TRUE, '2026-09-28', FALSE, NULL, FALSE, FALSE)
ON CONFLICT (user_id) DO UPDATE SET
  name = EXCLUDED.name,
  username = EXCLUDED.username,
  email = EXCLUDED.email,
  role = EXCLUDED.role,
  team = EXCLUDED.team,
  teams = EXCLUDED.teams,
  active = EXCLUDED.active,
  joined = EXCLUDED.joined,
  late_allowed = EXCLUDED.late_allowed,
  work_mode = EXCLUDED.work_mode,
  officer = EXCLUDED.officer,
  mto = EXCLUDED.mto;

INSERT INTO attendance (user_id, date, check_in, check_out, late, worked_minutes, marked_present)
VALUES ('PSS003', '2026-09-28', '2026-09-28T05:05:06.852Z'::timestamptz, NULL, TRUE, NULL, FALSE)
ON CONFLICT (user_id, date) DO NOTHING;

INSERT INTO attendance (user_id, date, check_in, check_out, late, worked_minutes, marked_present)
VALUES ('PSS016', '2026-09-28', '2026-09-28T09:11:14.827Z'::timestamptz, NULL, TRUE, NULL, FALSE)
ON CONFLICT (user_id, date) DO NOTHING;

INSERT INTO tasks (id, title, brief, description, assignee_user_id, status, priority, due_date, created_by, created_at, updated_at, completed_at)
VALUES ('0aaa439c-07f9-450e-be9c-fac57a27dd93', 'defense', 'fdgjfl', '', 'PSS015', 'open', 'medium', NULL, 'PSS001', '2026-10-09T07:06:06.651Z'::timestamptz, '2026-10-09T07:43:40.711Z'::timestamptz, NULL)
ON CONFLICT (id) DO NOTHING;

INSERT INTO tasks (id, title, brief, description, assignee_user_id, status, priority, due_date, created_by, created_at, updated_at, completed_at)
VALUES ('3a1a59d6-e185-4ab4-a154-7b4070b1b1c3', 'inncident', 'jhjhh', '', 'PSS015', 'done', 'medium', NULL, 'PSS001', '2026-10-09T07:06:40.380Z'::timestamptz, '2026-10-09T07:21:06.046Z'::timestamptz, '2026-10-09T07:21:06.035Z'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO tasks (id, title, brief, description, assignee_user_id, status, priority, due_date, created_by, created_at, updated_at, completed_at)
VALUES ('cf650a5d-f4a6-46fc-bc33-e23e4960a2a3', 'cipher', 'dsgf', '', 'PSS013', 'open', 'medium', NULL, 'PSS001', '2026-10-09T07:06:55.840Z'::timestamptz, '2026-10-09T07:06:55.840Z'::timestamptz, NULL)
ON CONFLICT (id) DO NOTHING;

INSERT INTO task_activity (id, task_id, actor_user_id, kind, detail, created_at)
VALUES ('694487ee-c697-4ea9-a8a4-435066e44b71', '0aaa439c-07f9-450e-be9c-fac57a27dd93', 'PSS001', 'created', 'Assigned to Talha Obaid', '2026-10-09T07:06:06.666Z'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO task_activity (id, task_id, actor_user_id, kind, detail, created_at)
VALUES ('7061b960-24e2-46a8-b615-f303110dd14e', '3a1a59d6-e185-4ab4-a154-7b4070b1b1c3', 'PSS001', 'created', 'Assigned to Talha Obaid', '2026-10-09T07:06:40.381Z'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO task_activity (id, task_id, actor_user_id, kind, detail, created_at)
VALUES ('2c1a9884-cab5-4fda-a47b-b9c2f925033c', 'cf650a5d-f4a6-46fc-bc33-e23e4960a2a3', 'PSS001', 'created', 'Assigned to Abeera Zainab', '2026-10-09T07:06:55.841Z'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO task_activity (id, task_id, actor_user_id, kind, detail, created_at)
VALUES ('0f445aca-db0b-46a9-a63f-3d6c61af3499', '3a1a59d6-e185-4ab4-a154-7b4070b1b1c3', 'PSS001', 'status', 'Done', '2026-10-09T07:09:46.648Z'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO task_activity (id, task_id, actor_user_id, kind, detail, created_at)
VALUES ('50d00519-a3db-422a-b240-7ea8a207b104', '0aaa439c-07f9-450e-be9c-fac57a27dd93', 'PSS001', 'status', 'In progress', '2026-10-09T07:09:49.326Z'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO task_activity (id, task_id, actor_user_id, kind, detail, created_at)
VALUES ('0b8cdf53-507e-499e-a3eb-8de0b29e83a1', '3a1a59d6-e185-4ab4-a154-7b4070b1b1c3', 'PSS001', 'status', 'In progress', '2026-10-09T07:11:25.033Z'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO task_activity (id, task_id, actor_user_id, kind, detail, created_at)
VALUES ('c5821664-9538-4c60-b094-cd38557fc342', '3a1a59d6-e185-4ab4-a154-7b4070b1b1c3', 'PSS001', 'status', 'Done', '2026-10-09T07:21:06.049Z'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO task_activity (id, task_id, actor_user_id, kind, detail, created_at)
VALUES ('005fc39d-1375-437f-a235-2ca098baa633', '0aaa439c-07f9-450e-be9c-fac57a27dd93', 'PSS001', 'status', 'Done', '2026-10-09T07:41:46.985Z'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO task_activity (id, task_id, actor_user_id, kind, detail, created_at)
VALUES ('427265da-f34c-4f0e-8124-2124595b968f', '0aaa439c-07f9-450e-be9c-fac57a27dd93', 'PSS001', 'status', 'Open', '2026-10-09T07:43:40.712Z'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sheet_days (day, added_by, created_at)
VALUES ('2026-10-08', 'PSS001', '2026-10-09T07:20:54.812Z'::timestamptz)
ON CONFLICT (day) DO NOTHING;

INSERT INTO sheet_days (day, added_by, created_at)
VALUES ('2026-10-09', 'PSS001', '2026-10-09T07:20:48.008Z'::timestamptz)
ON CONFLICT (day) DO NOTHING;
